spring:
  datasource:
    url: jdbc:mysql://localhost:8080/ticket
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  output:
    ansi:
      enabled: ALWAYS


server:
  servlet:
    context-path: /halee

logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss})  %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

    level:
#      root: TRACE
      org:
        hibernate:
          type: TRACE
      com:
        arkeeta: TRACE

